# Generated by Django 2.2.2 on 2019-08-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190806_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'Admin'), ('1', 'journalist'), ('2', 'staff')], default='0', max_length=2),
        ),
    ]
